name: ecook
description: 减肥餐

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  # app 信息
  package_info: '>=0.4.1 <2.0.0'
  # 设备信息
  device_info: ^0.2.1
  # 网络
  dio: ^3.0.9
  json_annotation: ^2.0.0


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # app 信息
  package_info: '>=0.4.1 <2.0.0'
  # 设备信息
  device_info: ^0.2.1
  # 网络
  dio: ^3.0.9
  json_annotation: ^2.0.0

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # 图片
  assets:
    - assets/tab_home.png
    - assets/tab_home_def.png
    - assets/tab_sc.png
    - assets/tab_sc_def.png
    - assets/tab_zx.png
    - assets/tab_zx_def.png
    - assets/sc_pic1.png
    - assets/sc_pic2.png
    - assets/sc_pic3.png
    - assets/home_pic1.png
    - assets/home_pic2.png
    - assets/home_pic3.png
    - assets/zj_zan_def.png
    - assets/home_tab_sc.png
    - assets/home_js.png
    - assets/home_my.png
    - assets/home_ss.png
    - assets/sc_bj.png
    - assets/collection_edit_def.png
    - assets/collection_edit_select.png
    - assets/detail_back.png
    - assets/detail_add.png
    - assets/detail_zan.png
    - assets/detail_userbg.png
    - assets/jz_pic2.png
    - assets/other/

  # 字体
  fonts:
    - family: SourceHanSerifCN
      fonts:
        - asset: fonts/SourceHanSerifCN-Bold.otf
        - asset: fonts/SourceHanSerifCN-Medium.otf
